body:
  - type: textarea
    attributes:
      placeholder: Please be specific and polite :)
      label: Your question
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Addon version and details
      description: |
        ⚠️⚠️⚠️  What version of Video DownloadHelper are you using?
