body:
  - type: textarea
    attributes:
      placeholder: Please be specific and polite :)
      label: Your question
    validations:
      required: true
  - type: input
    validations:
      required: true
    attributes:
      label: Addon version
      description: |
        What version of Video DownloadHelper are you using?
